version: '3.8'

services:
  users:
    build: ./users
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      JWT_SECRET: supersecret

  products-primary:
    build: ./products
    ports:
      - "5002:5002"
    environment:
      PORT: 5002
      JWT_SECRET: supersecret
      DB_FILE: db-primary.json
      IS_REPLICA: "false"
      PRODUCTS_REPLICA_URL: http://products-replica:5012

  products-replica:
    build: ./products
    ports:
      - "5012:5012"
    environment:
      PORT: 5012
      JWT_SECRET: supersecret
      DB_FILE: db-replica.json
      IS_REPLICA: "true"

  orders:
    build: ./orders
    ports:
      - "5003:5003"
    environment:
      PORT: 5003
      JWT_SECRET: supersecret
      USERS_URL: http://users:5001
      PRODUCTS_URL: http://products-primary:5002
    depends_on:
      - users
      - products-primary

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      JWT_SECRET: supersecret
      USERS_URL: http://users:5001
      PRODUCTS_URL: http://products-primary:5002
      PRODUCTS_REPLICA_URL: http://products-replica:5012
      ORDERS_URL: http://orders:5003
    depends_on:
      - users
      - products-primary
      - products-replica
      - orders
